name: Test Advent Of Code

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: [2021, 2022]

    steps:
    -
      uses: actions/checkout@v3
    -
      name: Build Advent of Code ${{ matrix.year }}
      working-directory: ${{ matrix.year }}
      run: cargo build --verbose
    -
      name: Run tests for Advent of Code ${{ matrix.year }}
      working-directory: ${{ matrix.year }}
      run: cargo test --verbose

